#!/usr/bin/env php
<?php

require_once __DIR__. '/vendor/autoload.php';

use App\Commands\TaskCommand;
use Symfony\Component\Console\Application;

$application = new Application("Hourglass \xE2\x8C\x9B ", '0.1');

$command = new TaskCommand();

$application->add($command);

try {
    $application->run();
} catch (Exception $e) {
    echo $e;
}