services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Commands\:
    resource: '../src/Commands'
    tags: ['console.command']

  App\Helpers\:
    resource: '../src/Helpers'
